# Generated by Django 4.2.1 on 2023-06-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_and_social_security', '0002_alter_payment_options_alter_work_permit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='work_permit',
            name='reason_for_application',
            field=models.CharField(help_text='type in less than 200 characters', max_length=200),
        ),
    ]
