# Generated by Django 4.2.1 on 2023-06-11 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labour_and_social_security', '0003_contactmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
