# Generated by Django 4.2.1 on 2023-06-11 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labour_and_social_security', '0004_contactmessage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiters_License_and_Permits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='Recruiters License and Permit', max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason_for_application', models.CharField(help_text='type in less than 200 characters', max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.CharField(max_length=200)),
                ('company_telephone', models.CharField(max_length=200)),
                ('cv_pdf', models.FileField(help_text='file must be in single pdf file', upload_to='certificates/', verbose_name='CVs of potential Recruiter’s permit holders')),
                ('company_registration_doc', models.FileField(help_text='file must be in pdf', upload_to='certificates/', verbose_name='Company Registration Documents')),
                ('lease_agreement', models.FileField(help_text='file must be in pdf', upload_to='certificates/', verbose_name='Lease Agreement')),
                ('tax_clearance', models.FileField(help_text='file must be in pdf', upload_to='certificates/', verbose_name='Tax Clearance')),
                ('compensation', models.FileField(help_text='file must be in pdf', upload_to='certificates/', verbose_name='Copy of Workers Compensation Insurance Certificate')),
                ('bank_statement', models.FileField(help_text='file must be in pdf', upload_to='certificates/', verbose_name='Three (3) months Bank Statement')),
                ('ids', models.FileField(help_text='file must be in a single pdf file', upload_to='ids_and_passports/', verbose_name='Certified Identity Cards/ Work permits for Directors')),
                ('certified_copy_of_passport_pdf', models.FileField(upload_to='ids_and_passports/')),
                ('approval_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiters License and Permit',
                'verbose_name_plural': 'Recruiters License and Permits',
            },
        ),
    ]
