# Generated by Django 4.2.1 on 2023-06-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_and_social_security', '0005_recruiters_license_and_permits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiters_license_and_permits',
            name='certified_copy_of_passport_pdf',
        ),
        migrations.AlterField(
            model_name='work_permit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
