# Generated by Django 4.2.1 on 2023-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_and_social_security', '0006_remove_recruiters_license_and_permits_certified_copy_of_passport_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters_license_and_permits',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='work_permit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=10),
        ),
    ]
