# Generated by Django 4.2.1 on 2023-06-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_and_social_security', '0007_alter_recruiters_license_and_permits_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters_license_and_permits',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='BOTSWANA CURRENCY - BWP', max_digits=10),
        ),
        migrations.AlterField(
            model_name='work_permit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=250, help_text='BOTSWANA CURRENCY - BWP', max_digits=10),
        ),
    ]
