# Generated by Django 4.2.1 on 2023-06-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_and_social_security', '0008_alter_recruiters_license_and_permits_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recruiters_license_and_permits',
            name='service',
            field=models.CharField(choices=[('Application of Recruiter License', 'Application of Recruiter License'), ('Renewal of Recruiter License', 'Renewal of Recruiter License')], max_length=200),
        ),
        migrations.AlterField(
            model_name='work_permit',
            name='service',
            field=models.CharField(choices=[('Application of Work Permit', 'Application of Work Permit'), ('Renewal of Work Permit', 'Renewal of Work Permit')], max_length=200),
        ),
    ]
