# Generated by Django 4.2.1 on 2023-06-11 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labour_and_social_security', '0009_alter_payment_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence_Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Application of Residence Permit', 'Application of Residence Permit'), ('Renewal of Residence Permit', 'Renewal of Residence Permit')], max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason_for_application', models.CharField(help_text='type in less than 200 characters', max_length=200)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Widower', 'Widower'), ('Other', 'Other')], max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('work_permit_no', models.CharField(max_length=200)),
                ('number_of_children', models.IntegerField()),
                ('passport_number', models.CharField(max_length=200)),
                ('passport_number_expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('approval_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('cv_pdf', models.FileField(upload_to='cvs/')),
                ('certified_copy_of_passport_pdf', models.FileField(upload_to='ids_and_passports/')),
                ('certified_copy_of_certificates_pdf', models.FileField(upload_to='certificates/')),
                ('amount', models.DecimalField(decimal_places=2, default=250, help_text='BOTSWANA CURRENCY - BWP', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Permit',
                'verbose_name_plural': 'Work Permits',
            },
        ),
    ]
